// The texts, the names of the groups and their colors, as the explorer shows them.
import type { Region } from '../emoji';

export const words = {
  placeholder: 'Tell DAM1 LLM something ...',
  say: 'Say',
  controls: 'Play it back',
  foldControls: 'Hide the play-back',
  history: 'What was said',
  map: 'Map',
  mode: 'What you are doing',
  sayMark: '💬',
  reading: 'Reading',
  newGame: 'New...',
  newButton: '+ New',
  games: 'Discussions',
  noGames: 'No discussions yet. Start one.',
  empty: 'A new world! Say something.',
  showChat: 'Show chat',
  undo: 'Undo',
  undoTitle: 'Undo this turn?',
  undoHint: 'This turn and its answer are taken out of the game, and DAM1 reads the rest of the game again without it.',
  model: 'DAM1',
  bendHint: 'Press and drag to bend the line. Press a bend twice to take it out.',
  close: 'Close',
  recalling: 'Reading this chat again to get its moves.',
  home: 'home',
  stats: 'DAM1 LLM State',
  stands: 'Location',
  holds: 'Holding',
  pointsAt: 'Pointing at',
  notes: 'Notes',
  instant: 'Instant',
  instantHint: 'No play-back: a new turn shows its answer and the world at once',
  question: 'Question',
  noAnswer: 'No answer',
  labelTitle: 'Picture for',
  labelHint: 'Pick the picture this word is drawn with on the map. Leave it empty to go back to its own.',
  labelText: 'Picture (any emoji)',
  stackNow: 'The stack he sees now (newest on top)',
  stackWhole: 'Everything he did this turn (newest on top)',
  youTitle: 'How you are shown',
  youPicture: 'Picture (any emoji)',
  keep: 'Keep',
  curious: 'Curious about',
  change: 'Change',
  worldPlaceholder: 'Update the world without DAM1 knowing ...',
  worldMark: '🌍',
  analytics: 'Stack',
  counts: 'Analytics',
  network: 'The network',
  voters: 'Networks that vote',
  weights: 'Weights',
  downloadSize: 'Download, zipped',
  weightSize: 'Weights, unzipped',
  engineSize: 'Size of the engine',
  knowledge: 'Nodes of knowledge',
  knowledgeSize: 'Size of the knowledge',
  movesKnown: 'Moves it can take',
  hiddenWidth: 'Hidden width',
  stackSlots: 'Stack slots',
  turnsSaid: 'Turns',
  questions: 'Questions asked',
  relations: 'Relations drawn',
  groupsShown: 'Groups',
  stackSize: 'Items on the stack',
  output: 'Output',
  rename: 'Rename',
  saveAs: 'Save as',
  remove: 'Delete',
  removeAsk: 'Delete this game? The chat and all it told him are gone for good.',
  cancel: 'Cancel',
  copyOf: (title: string) => `${title} (copy)`,
  name: 'Name',
  speed: 'Solve speed',
  toEnd: 'to the end',
  nothing: 'nothing',
  heard: 'Words heard',
  moved: 'Moves taken',
  things: 'Things on the map',
  memorized: 'Overview',
  memorizedNone: 'Nothing yet.',
};

export const regionNames: Record<Region, string> = {
  people: 'People', animals: 'Animals', food: 'Food', things: 'Things', places: 'Places', nature: 'Nature and sky', qualities: 'Qualities', numbers: 'Numbers and amounts', doing: 'Doing', time: 'When',
};
export const regionTints: Record<Region, string> = {
  people: 'rgba(255, 143, 177, 0.08)', animals: 'rgba(255, 170, 90, 0.08)', food: 'rgba(255, 99, 99, 0.07)', things: 'rgba(255, 209, 102, 0.07)',
  places: 'rgba(90, 170, 255, 0.08)', nature: 'rgba(120, 220, 140, 0.08)', qualities: 'rgba(190, 140, 255, 0.08)', numbers: 'rgba(120, 230, 230, 0.07)', doing: 'rgba(255, 255, 255, 0.06)', time: 'rgba(255, 190, 120, 0.08)',
};
export const regionInks: Record<Region, string> = {
  people: '#ff8fb1', animals: '#ffaa5a', food: '#ff7a7a', things: '#ffd166', places: '#5aaaff', nature: '#78dc8c', qualities: '#be8cff', numbers: '#78e6e6', doing: '#d8dee9', time: '#ffbe78',
};
